using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BTRReportProcesser.Assets
{
    public static class CommentLookupTable
    {
        public static readonly Dictionary<String, String> Table = new Dictionary<string, string>()
        {
            { "", "" },
            { "Maneuver was not started from TLC, FIVC is greater than FVC (FEV1 and FVC).", "SIE" },
            { "After deep breath instruct subject to BLAST the air out without a hesitation.", "Start of test" },
            { "There multiple efforts performed in Act 1. Please only perform one PFT maneuver for each act.", "Performing multiple maneuvers" },
            { "Please do not have the subject perform the \"Open Circuit\" technique. Have the subject perform relaxed tidal breathing before the FVC maneuver.", "Open Circuit " },
            { "Please have the subject perform relaxed tidal breathing before the deep inspiration followed by the FVC maneuver", "Start of test" },
            { "This is an unacceptable coaching technique and should be discontinued", "End of test" },
            { "Hesitation during start of forced exhalation back extrapolated volume is out of range (FEV1 and FVC)", "Start of test" },
            { "Subject did not reach plateau at end exhalation, FVC may be underestimated (FVC)", "FVC may be underestimated" },
            { "This is an unacceptable coaching technique and should be stopped.", "End of test" },
            { "Please only perform 1 forced effort per act.  It appears there are multiple forced exhalations on each act.", "Performing multiple maneuvers" },
            { "Looking at the RAW data there are several linked efforts coached in Acts 1 and 3-7.", "Performing multiple maneuvers" },
            { "Please only coach one PFT maneuver in each act", "Performing multiple maneuvers" },
            { "There are multiple efforts and very large tidal breaths performed. There shouold be relaxed tidal breathing before the FVC maneuver", "Performing multiple maneuvers" },
            { "The tidal breaths are large compared to the FVC maneuver. Please coach smaller, relaxed tidal breathing before the FVC maneuver", "Start of test" },
            { "There are multiple linked efforts coached in each Act, please coach only one PFT effort in each Act", "Performing multiple maneuvers" },
            { "Please coach only one effort in each Act", "Performing multiple maneuvers" },
            { "Artifact/Cough during first second of effort (FEV1)", "Artifact/Cough" },
            { "Artifact/Cough during effort. Have subject rest between efforts to try and reduce cough.", "Artifact/Cough" },
            { "Abrupt end of exhalation (FVC)", "End of test" },
            { "Poor subject effort (FEV1 and FVC)", "Poor subject effort" },
            { "Have subject continue to exhale until lungs are empty or until they can\"\"t continue any longer.", "End of test" },
            { "Subject did not reach plateau at enexhalation, FVC may be underestimated (FVC)", "FVC may be underestimated" },
            { "Please have subject close the loop by taking a deep inhalation after the full exhalation", "End of test" },
            { "Poor start of effort, late time to peak flow (FEV1)", "Start of test" },
            { "After deep breath instruct subject to BLAST the air out without a hesitation.Poor start of effort; late time to peak flow (FEV1)", "Start of Test" },
            { "Poor start of effort; late time to peak flow (FEV1)", "Start of Test" },
            { "Poor Inspiratory effort; have subject take deep and complete breath in prior to forceful exhalation.Maneuver was not started from TLC; FIVC is greater than FVC (FEV1 and FVC).", "SIE" },
            { "Please have subject close the loop by taking a deep inhalation after the full exhalationManeuver was not started from TLC; FIVC is greater than FVC (FEV1 and FVC).", "SIE" },
            { "Artifact/Cough during effort (FVC)", "Artifact/Cough" },
            { "Hesitation during start of forced exhalation back extrapolated volume is out of range (FEV1)", "Start of test" },
            { "Poor inspiratory effort.", "4th Phase" },
            { "Poor Inspiratory effort, have subject take deep and complete breath in prior to forceful exhalation.", "SIE" },
            { "Perform additional efforts; up to a maximum of eight to reach repeatability.", "Less than 3 acceptable" },
            { "Perform additional efforts, up to a maximum of eight to reach repeatability.", "Less than 3 acceptable" },
            { "Perform additional efforts up to a maximum of eight to reach repeatability", "Less than 3 acceptable" },
            { "Baseline drift (FEV1 and FVC)", "Baseline drift" },
            { "Patient CANNOT be randomized; because data does not meet the ATS/ERS criteria for acceptable data quality at screening visit.", "Bad Test" },
            { "Patient CANNOT be randomized; because FVC data does not meet the ATS/ERS criteria for acceptable data quality at screening visit.", "Bad Test" },
            { "Best FVC: Acceptable effort deselected by site (FVC)", "Bad Effort" },
            { "Some drift during tidal breathing is noted. Please make sure subject is wearing noseclips and has a good seal on mouthpiece.", "Baseline drift" },
            { "Please coach the subject to complete the 4th phase to TLC by taking a big breath in to TLC after the forced exhalation", "Fourth Phase" },
            { "Coaching multiple linked efforts in a single Act is an unacceptable coaching technique. Please coach only one effort in each Act.", "Performing multiple maneuvers" },
            { "Please make sure subject is wearing noseclips and has a good seal on mouthpiece.", "Baseline drift" },
            { "There maybe an issue with baseline drift and zeroing of the pneumotach", "Baseline drift" },
            { "There are two linked efforts coached in all Acts; please coach only one effort in each Act", "Performing multiple maneuvers" },
            { "After the 2nd inspiration the subject should go back to relaxed tidal breathing. Please return to normal tidal breathing and do not perform a second forced exhalation", "Performing multiple maneuvers" },
            { "There is abrupt end of inhalation on all efforts. The subject is ending the inhalation after the forced exhalation too soon.", "End of test" },
            { "Please make sure the pneumotach is not reversed before testing subjects", "Pneumotach reversed " },
            { "Please do not coach an ERV maneuver prior to the deep inhalation to TLC before the forced exhalation", "Exhaling to ERV" },
            { "There are two linked efforts coached in all Acts please coach only one effort in each Act", "Performing multiple maneuvers" },
            { "The subject must complete the 4th phase to TLC by taking a big breath in to TLC after the forced exhalation", "Fourth Phase" },
            { "Coaching multiple linked efforts and large tidal breaths in a single Act is an unacceptable coaching technique and may exhaust the subject.  Please coach only one effort in each Act.", "Performing multiple maneuvers" },
            { "Please coach smaller; relaxed tidal breathing before the forced maneuver", "Tidal Breathing Error" },
            { "Some significant drift during tidal breathing is noted. Please make sure subject is wearing noseclips and has a good seal on mouthpiece.", "Baseline drift" },
            { "FEV1 is not repeatable", "Repeatability" },
            { "FVC is not repeatable", "Repeatability" },
            { "Please coach up to eight efforts to achieve acceptability and repeatability if tolerated by the subject.", "Less than 3 acceptable" },
            { "submaximal efforts FIVC significanty greater than FVC", "SIE" },
            { "Please perform acts from same subject", "Possible Mix up of subjects" },
            { "FVC and FEV1 are not repeatable within 150cc", "Repeatability" },
            { "Please have the test subject exhale to a one second plateau", "End of test" },
            { "Please do not perform the \"Open Circuit\" technique; use closed circuit technique. Have the subject perform relaxed tidal breathing while on the mouthpiece followed by the FVC maneuver.", "Tidal Breathing Error" },
            { "Subject breathing on wrong side of pneumotach (FEV1 and FVC)", "Pneumotach reversed " },
            { "Abrupt end of exhalation (FEV1)", "End of test" },
            { "Abrupt end of exhalation (FEV1 and FVC)", "End of test" },
            { "Poor Inspiratory effort; have subject take deep and complete breath in prior to forceful exhalation.", "Start of test" },
            { "Baseline drift; ensure nose clips are on and the subject has a tight seal around mouth piece.", "Baseline drift" },
            { "Please perform at least 3 acceptable efforts with no error codes.", "Less than 3 acceptable" },
            { "Pneumotach reversed; ensure the picture of the person is facing the subject.", "Pneumotach reversed " }
        };
    }
}
